---
- name: install docker apps
  hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: ensure docker packages is present
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      tags:
        - docker

    - name: ensure dockers official GPG is present
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - docker

    - name: ensure we have correct fingerprint key
      apt_key:
        id: 0EBFCD88
        state: present
      tags:
        - docker

    - name: get release
      command: lsb_release -sc
      register: release

    - name: ensure we have stable repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ release.stdout }} stable
        state: present
        update_cache: yes
      tags:
        - docker

    - name: ensure apt packages is updated
      apt:
        update_cache: yes
      tags:
        - docker

    - name: ensure docker is present
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      tags:
        - docker

    - name: get uname -s
      command: uname -s
      register: unames

    - name: get uname -m
      command: uname -m
      register: unamem

    - name: ensure docker-compose is present
      get_url:
        url: https://github.com/docker/compose/releases/download/1.28.6/docker-compose-{{ unames.stdout }}-{{ unamem.stdout }}
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
      tags:
        - docker

# - name: prepare duild environment
#   hosts: build
#   become: yes
#   gather_facts: false

#   tasks:
#     - name: ensure dcompose is present
#     apt:
#       name: docker-compose




